[package]
name = "my_macros"
version = "0.0.42"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.81" , features = ["full"] }
quote = "1.0.10"
proc-macro2 = "1.0.32"
